config/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import LoginView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("pages.urls", namespace="pages")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("user/", include("users.urls", namespace="user")),
    # path("user/ajaxlogin/", LoginView.as_view()),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = "pages"

urlpatterns = [
    path("", TemplateView.as_view(template_name="main.html"), name="home"),
    path(
        "branch/isu",
        TemplateView.as_view(template_name="branch/branch_isu.html"),
    ),
    path("intro/branch", views.BranchView.as_view(), name="branch"),
    path("intro/ci", TemplateView.as_view(template_name="intro/intro_ci.html")),
    path("intro", TemplateView.as_view(template_name="intro/intro.html")),
    path("implant/type/", TemplateView.as_view(template_name="imp/imp_type.html")),
    path("implant", TemplateView.as_view(template_name="imp/imp.html")),
    path("align/type/", TemplateView.as_view(template_name="align/align_type.html")),
    path("align", TemplateView.as_view(template_name="align/align.html")),
    path("beauty/1day", TemplateView.as_view(template_name="beauty/beauty_1day.html")),
    path("beauty", TemplateView.as_view(template_name="beauty/beauty.html")),
    path("general/type/", TemplateView.as_view(template_name="gnral/gnral_type.html")),
    path("general", TemplateView.as_view(template_name="gnral/gnral.html")),
]

posts/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "posts"

urlpatterns = [
    # path("notice", TemplateView.as_view(template_name="posts/notice.html")),
    path("notice", views.NoticeView.as_view(), name="notice"),
    path("notice/search", views.NoticeSearch, name="notice_search"),
    path(
        "notice/<int:pk>",
        views.NoticeDetail.as_view(),
        name="notice_detail",
    ),
    path("beforeafter", views.BnAView.as_view(), name="bna"),
    path("beforeafter/search", views.BnASearch, name="bna_search"),
    path(
        "beforeafter/<int:pk>",
        views.BnADetail.as_view(),
        name="bna_detail",
    ),
    path("qna", views.QnaView.as_view(), name="qna"),
    path("qna/check", views.QnaCheckView, name="qna_check"),
    path("qna/create", views.CreateQnaView.as_view(), name="qna_create"),
    path("qna/<int:pk>", views.QnaDetail.as_view(), name="qna_detail"),
    path(
        "qna/<int:pk>/a_create",
        views.CreateQnaAnswerView.as_view(),
        name="qna_a_create",
    ),
    path("qna/<int:pk>/a_delete", views.qna_a_delete, name="qna_a_delete"),
    path("qna/<int:pk>/a_edit", views.QnaAnswerEditView.as_view(), name="qna_a_edit"),
    path("news", views.NewsView.as_view(), name="news"),
    path(
        "news/<int:pk>",
        views.NewsDetail.as_view(),
        name="news_detail",
    ),
]

templates/mixins/bna_list.html
<li class="b_pic" onclick="window.location.href = '/posts/beforeafter/{{bna.pk}}'" style="cursor:pointer;"> 
    <div class="pic">
        {% for photo in bna.get_photos %}
            <img style="position:absolute; z-index:-1;width: 100%;height: 100%;" src="{{ MEDIA_URL }}{{photo.file.url}}" alt="치료 후 사진">
        {% endfor %}
        {% if not user.is_authenticated %}
            <div class="text">
                <p>의료법상 치료사례 확인은 로그인 후 가능합니다.</p>
                <div class="icon" style="text-align: center; width: 100%;">
                    <a href="/auth/kakao/login/?method=oauth2&amp;next=/beforeafter/">
                        <img src="//cdn.gdaj.net/dentalweb/cdn/statics/img/assets/kakao_af.png" alt="카카오 아이콘">
                    </a>
                    <a href="/auth/naver/login/?method=oauth2&amp;next=/beforeafter/">
                        <img src="//cdn.gdaj.net/dentalweb/cdn/statics/img/assets/naver.png" alt="네이버 아이콘">
                    </a>
                    <a href="javascript:;" class="login_btn_pop">  
                        <img src="//cdn.gdaj.net/dentalweb/cdn/statics/img/assets/login.png" alt="로그인 아이콘">
                    </a>
                </div>
            </div>
        {% endif %}
    </div>
    <p class="cap"><span class="cap__category">[{{bna.bna_type}}]</span> {{bna.title}}</p>
</li>

templates/mixins/news_list.html
<tr>
        <td>{{news.pk}}</td>
        <td class="title">
            <a href="{% url 'posts:news_detail' news.pk %}">
                <p class="text_overflow w_530">[{{news.content}}]{{news.title}}</p>
            </a>
        </td>
        <td>{{news.created|date:'Y.m.d'}}</td>
</tr>
    

templates/mixins/notice_list.html
<tr>
    <td>{{notice.notice_type}}</td>
    <td class="title">
        <a href="{%url 'posts:notice_detail' notice.pk %}">
            <p class="text_overflow w_760">
                {{notice.title}}
            </p>
        </a>
    </td>
    <td>
        <p class="text_overflow w_200">
            {{notice.host.username}}
        </p>
    </td>
    <td>{{notice.created|date:'Y.m.d'}}</td>
</tr>

templates/mixins/paging.html
<div class="paging">
    <span class="paging_control">
        <a {% if page_obj.has_previous %}href="?page=1" class="paging-first active"{% endif %} class="paging-first"></a>
        <a {% if page_obj.has_previous %}href="?page={{page_obj.previous_page_number}}" class="paging-prev active"{% endif %} class="paging-prev"></a>
    </span>
    <span id="pagingnumber">
        {% for index in pagelist %}
            {% if index == page_obj.number %}
                <a href class="active">{{ index }}</a>
            {% else %}
                <a href="?page={{ index }}">{{ index }}</a>
            {% endif %}
        {% endfor %}
    </span>    
    <span class="paging_control">
        <a {% if page_obj.has_next %}href="?page={{page_obj.next_page_number}}"{% else %}style="opacity:0.2;"{% endif %} class="paging-next"></a>
        <a {% if page_obj.has_next %}href="?page={{page_obj.paginator.num_pages}}"{% else %}style="opacity:0.2;"{% endif %} class="paging-last"></a>
    </span>
</div>

templates/mixins/qna_list.html
<tr onclick="$('.c_tr_secret').hide(); $('.secret_{{qna.pk}}').toggle();" style="cursor: pointer">
                            
    <td>{{qna.branch}}</td>
    <td>{{qna.care_type}}</td>
    <td class="title">
        <p class="text_overflow w_580">
            {{qna.title}}
        </p>
    </td>
    <td>
        
            <p class="p_c_status">
                {% if qna.answer_text %}
                    <span class="c_status c_s_complete">상담완료</span>
                {% else %}
                    <span class="c_status c_s_wait">상담대기</span>
                {% endif %}
            </p>
        
    </td>
    <td>{{qna.name}}</td>
    <td>{{qna.created|date:'Y.m.d'}}</td>
</tr>
<tr class="c_tr_secret secret_{{qna.pk}}" style="display: none;">
    <td colspan="2"></td>
    <td colspan="4" class="title">
        <div class="secret_text">비공개 글입니다.</div>
        <div>
            
                <input type="password" name="qna_passwd" placeholder="비밀번호를 입력해주세요." class="qna_passwd" id="secret_password_{{qna.pk}}" data-pk="{{qna.pk}}" required="">
            
            <button type="button" class="btnSubmit" onclick="CheckSubmit('{{qna.pk}}')" style="cursor: pointer;">확인</button>
        </div>
    </td>
</tr>

templates/mixins/sub_script.html
<script src="/static/js/sub.js"></script>
<script>
    $(document).ready(function () {
        // main menu 대표, 지점 관련 jquery
        $("#main_top_category").mouseenter(function () {
            $('#main_top_category_sub').css({
                'display': 'block'
            });
            return false;
        });

        $('#main_top_category_sub').mouseleave(function () {
            $('#main_top_category_sub').fadeOut();
            return false;
        });
        $(".login_btn_pop").click(function () {
            $('#login').show();
            return false;
        });
    });
</script>

templates/mixins/sub_style.html
{% load static %}
<script>
    $(document).ready(function(){
        if(window.location.hash ) scroll(0,0);
        setTimeout( function() { scroll(0,0); }, 1);
        $(function() {    
            if(window.location.hash) {
                $('html, body').animate({
                    scrollTop: $(window.location.hash).offset().top-200 + 'px'
                }, 1000, 'swing');
            }
        });
    })
</script>
<script type="text/javascript">
    const popChunkUp = (elem) => {
        document.getElementById(elem.dataset.target).classList.add('show')
    }
    const popChunkDown = (elem) => {
        document.querySelectorAll('.popup-wrapper').forEach((elem) => elem.style.display = 'none');
        document.querySelectorAll('.popup-wrapper').forEach((elem) => elem.classList.remove('show'));
    };
</script>
<link rel="stylesheet" href="{% static "css/sub.css" %}" />
<style>
    .show {
        display: block !important;
    }

    #login {
        display: none;
    }

    .cont {
        display: flex;
        flex-flow: row wrap;
        justify-content: center;
        overflow: hidden;
        position: absolute;
        width: 1000px;
        height: 700px;
        padding: 0;
        box-sizing: border-box;
        background-color: white;
    }

    .cont .tlogo {
        width: 1000px;
        height: 80px;
        background: var(--bg-popupwrap) center center no-repeat;
        background-size: cover;
    }

    .cont .text {
        box-sizing: border-box;
    }

    .cont .close {
        width: 135px;
        height: 55px;
        line-height: 55px;
        margin: -30px auto 0;
        text-align: center;
        border: 1px solid rgb(48, 48, 48);
        background-color: rgb(255, 255, 255);
        font-size: 18px;
        letter-spacing: -0.03em;
    }

    .cont h1 {
        text-align: center;
        margin-bottom: 15px;
        font-weight: 700;
        font-size: 40px;
        letter-spacing: -0.065em;
        color: #333333;
        width: 100%;
    }

    .popup-wrap .closebtn {
        position: absolute;
        top: 24px;
        right: 24px;
    }

    .cont .txt {
        overflow-y: scroll;
        /* overflow-y: auto; */
        width: 910px;
        height: 400px;
        line-height: 28px;
        padding: 30px 20px 30px 30px;
        border-top: 2px solid #000000;
        border-bottom: 2px solid rgb(222, 222, 222);
        box-sizing: border-box;
        background-color: #fbfbfb;
        white-space: pre-line;
        word-break: keep-all;
        font-size: 14px;
        letter-spacing: -0.045em;
        color: #666666;
    }
    /* 스크롤바 수정 _ 크롬, 사파리(웹킷 엔진)  */
    .cont .txt::-webkit-scrollbar{
        width: 6px;
        height: auto;
    }

    .cont .txt::-webkit-scrollbar-thumb{
        border-radius: 8px;
        background-color: rgb(204, 204, 204);
    }

    .cont .txt::-webkit-scrollbar-track{
        border-radius: 8px;
        background-color: #ede8e2;

    }
    /* 스크롤바 수정 _ 파이어폭스 */
    .cont .txt{
        scrollbar-width: thin;
        scrollbar-color: rgb(204, 204, 204) #ede8e2;
    }
    /* 스크롤바 수정 e */
    
    .cont .txt .title {
        font-weight: 700;
        font-size: 15px;
        color: #000000;
    }

    .cont .close {
        width: 135px;
        height: 55px;
        line-height: 55px;
        margin: -30px auto 0;
        text-align: center;
        border: 1px solid rgb(48, 48, 48);
        background-color: rgb(255, 255, 255);
        font-size: 18px;
        letter-spacing: -0.03em;
    }

    .cont .close a {
        display: block;
    }
</style>