config/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import LoginView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("pages.urls", namespace="pages")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("user/", include("users.urls", namespace="user")),
    # path("user/ajaxlogin/", LoginView.as_view()),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = "pages"

urlpatterns = [
    path("", TemplateView.as_view(template_name="main.html"), name="home"),
    path(
        "branch/isu",
        TemplateView.as_view(template_name="branch/branch_isu.html"),
    ),
    path("intro/branch", views.BranchView.as_view(), name="branch"),
    path("intro/ci", TemplateView.as_view(template_name="intro/intro_ci.html")),
    path("intro", TemplateView.as_view(template_name="intro/intro.html")),
    path("implant/type/", TemplateView.as_view(template_name="imp/imp_type.html")),
    path("implant", TemplateView.as_view(template_name="imp/imp.html")),
    path("align/type/", TemplateView.as_view(template_name="align/align_type.html")),
    path("align", TemplateView.as_view(template_name="align/align.html")),
    path("beauty/1day", TemplateView.as_view(template_name="beauty/beauty_1day.html")),
    path("beauty", TemplateView.as_view(template_name="beauty/beauty.html")),
    path("general/type/", TemplateView.as_view(template_name="gnral/gnral_type.html")),
    path("general", TemplateView.as_view(template_name="gnral/gnral.html")),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("ajaxlogin/", views.ajax_login, name="ajaxlogin"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("logout", views.log_out, name="logout"),
]

posts/models.py
from django.db import models
from core import models as core_models
from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse


class AbstractItem(core_models.TimeStampedModel):

    """Abstract Item"""

    name = models.CharField(max_length=50)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


# class CareType(AbstractItem):

#     """CareType Model Definition"""

#     class Meta:
#         verbose_name = "Care Type"


class BnAPhoto(core_models.TimeStampedModel):

    """BnAPhoto Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="bna_photos")
    bna = models.ForeignKey(
        "BnAPost", related_name="bna_photos", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.caption


class BnAPost(core_models.TimeStampedModel):

    """Post Model Definition"""

    TYPE_EVENT = "치아교정"
    TYPE_NOTICE = "치아미백"

    TYPE_CHOICES = (
        (TYPE_EVENT, "치아교정"),
        (TYPE_NOTICE, "치아미백"),
    )
    title = models.CharField(max_length=80)
    bna_type = models.CharField(choices=TYPE_CHOICES, max_length=20)
    # care_type = models.ForeignKey(
    #     "CareType", related_name="posts", on_delete=models.CASCADE, blank=True
    # )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:beforeafter_detail", kwargs={"pk": self.pk})

    def get_photos(self):
        try:
            photos = self.bna_photos.all()
            return photos
        except ValueError:
            return None


class NoticePhoto(core_models.TimeStampedModel):

    """NoticePhoto Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="n_photos")
    notice = models.ForeignKey(
        "NoticePost", related_name="notice_photos", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.caption


class NoticePost(core_models.TimeStampedModel):

    """Post Model Definition"""

    TYPE_EVENT = "이벤트"
    TYPE_NOTICE = "공지"

    TYPE_CHOICES = (
        (TYPE_EVENT, "event"),
        (TYPE_NOTICE, "notice"),
    )
    title = models.CharField(max_length=80)
    text = models.TextField()
    host = models.ForeignKey(
        "users.User", related_name="notice", on_delete=models.CASCADE
    )
    notice_type = models.CharField(choices=TYPE_CHOICES, max_length=20)
    # care_type = models.ForeignKey(
    #     "CareType", related_name="posts", on_delete=models.CASCADE, blank=True
    # )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:notice_detail", kwargs={"pk": self.pk})

    def get_photos(self):
        try:
            photos = self.notice_photos.all()
            return photos
        except ValueError:
            return None


class QnaAnswerPost(core_models.TimeStampedModel):

    """QnaAnswerPost Model Definition"""

    answer_text = models.TextField(blank=True)
    qnas = models.ForeignKey(
        "QnaPost", related_name="answers", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.answer_text

    def get_absolute_url(self):
        return reverse("posts:qna_detail", kwargs={"pk": self.qnas.pk})


class QnaPost(core_models.TimeStampedModel):

    """Post Model Definition"""

    TYPE_GNRAL = "일반치료"
    TYPE_IMP = "임플란트"
    TYPE_ALIGN = "치아교정"
    TYPE_BEAUTY = "치아미백"

    TYPE_CHOICES = (
        (TYPE_GNRAL, "일반치료"),
        (TYPE_IMP, "임플란트"),
        (TYPE_ALIGN, "치아교정"),
        (TYPE_BEAUTY, "치아미백"),
    )
    title = models.CharField(max_length=80)
    text = models.TextField()
    branch = models.ForeignKey(
        "pages.Branch", related_name="qna", on_delete=models.CASCADE
    )
    care_type = models.CharField(choices=TYPE_CHOICES, max_length=20)
    name = models.CharField(max_length=50)
    phone = PhoneNumberField(region="KR")
    email = models.EmailField(max_length=50, blank=True)
    password = models.CharField(max_length=50)
    host = models.ForeignKey(
        "users.User",
        related_name="qna",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    answer_text = models.ForeignKey(
        "QnaAnswerPost",
        related_name="qna",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    # care_type = models.ForeignKey(
    #     "CareType", related_name="posts", on_delete=models.CASCADE, blank=True
    # )

    # def qna_answer(self):
    #     answer_text = self.answers.all()
    #     return answer_text

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:qna_detail", kwargs={"pk": self.pk})


class NewsPhoto(core_models.TimeStampedModel):

    """NewsPhoto Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="news_photo")
    notice = models.ForeignKey(
        "NewsPost", related_name="news_photos", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.caption


class NewsPost(core_models.TimeStampedModel):

    """Post Model Definition"""

    title = models.CharField(max_length=80)
    text = models.TextField()
    content = models.CharField(max_length=40)
    news_url = models.URLField(max_length=500)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:news_detail", kwargs={"pk": self.pk})

    def get_photos(self):
        try:
            photos = self.news_photos.all()
            return photos
        except ValueError:
            return None

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):

    superhost = models.BooleanField(default=False)

users/forms.py
from django import forms
from . import models
import re


class LoginForm(forms.Form):

    username = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "ID", "id": "login_username"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호", "id": "login_password"}
        )
    )

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(username=username)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("username", forms.ValidationError("User does not exist"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("username", "email")
        widgets = {
            "username": forms.TextInput(),
            "email": forms.EmailInput(),
        }

    password = forms.CharField(widget=forms.PasswordInput())
    password1 = forms.CharField(widget=forms.PasswordInput())

    def clean_username(self):
        username = self.cleaned_data.get("username")
        try:
            models.User.objects.get(username=username)
            raise forms.ValidationError(
                "That username is already taken", code="existing_user"
            )
        except models.User.DoesNotExist:
            return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError(
                "That email is already taken", code="existing_user"
            )
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        elif (
            len(password) < 8
            or len(password) > 21
            and not re.findall("[0-9]+", password)
            and not re.findall("[a-z]", password)
        ):
            raise forms.ValidationError(
                "Password 기준(8자리 이상 21자리 미만, 숫자,영문,대소문자 구성)에 맞지 않습니다."
            )
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user.username = username
        user.set_password(password)
        user.save()

users/views.py
from multiprocessing import AuthenticationError
from django.shortcuts import render, reverse, redirect, resolve_url
from django.views.generic import FormView
from . import mixins, forms, models
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.http import HttpResponse
import json


def ajax_login(request):
    if request.method == "POST":
        form = forms.LoginForm(request.POST)
        response_data = {}
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)

            if user is not None:
                form = forms.LoginForm()
                login(request, user)
                response_data["result"] = "Success!"
                response_data["message"] = 'You"re logged in'
            else:
                response_data["errors"] = "failed"
                response_data["captcha"] = "dd"
                response_data["message"] = "You messed up"
            return HttpResponse(
                json.dumps(response_data), content_type="application/json"
            )
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    # username = request.GET.get("username")
    # password = request.GET.get("password")
    # user = authenticate(username=username, password=password)
    # response_data = {}
    # if user.is_active:
    #     response_data["result"] = "Success!"
    #     response_data["message"] = 'You"re logged in'
    # else:
    #     response_data["errors"] = True
    #     response_data["captcha"] = True
    #     response_data["message"] = "You messed up"

    # return HttpResponse(json.dumps(response_data), content_type="application/json")


class LoginView(mixins.LoggedOutOnlyView, FormView):
    form_class = forms.LoginForm
    # template_name = "users/login.html"
    template_name = "main.html"
    success_url = "/user/ajaxlogin/"

    def form_invalid(self, form):
        response = super(LoginView, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(
                data={"result": False, "errors": form.errors}, safe=True, status=400
            )
        else:
            return response

    def form_valid(self, form):
        response = super(LoginView, self).form_valid(form)
        if self.request.is_ajax():
            print(response)
            # data = {"message": "Successfully submitted form data."}
            return JsonResponse(data={"result": True}, safe=True, status=200)
        else:
            return response


# class LoginView(mixins.AjaxFormMixin, FormView):
#     form_class = forms.LoginForm
#     # template_name = "users/login.html"
#     template_name = "main.html"
#     success_url = "/user/ajaxlogin/"

#     def form_invalid(self, form):
#         response = super(LoginView, self).form_invalid(form)
#         if self.request.is_ajax():
#             return JsonResponse(form.errors, status=400)
#         else:
#             return response

#     def form_valid(self, form):
#         response = super(LoginView, self).form_valid(form)
#         if self.request.is_ajax():
#             print(response)
#             data = {"message": "Successfully submitted form data."}
#             return JsonResponse(data)
#         else:
#             return response


# class LoginView(FormView):
#     template_name = "users/login.html"
#     form_class = forms.LoginForm

#     def form_valid(self, form):
#         username = form.cleaned_data.get("username")
#         password = form.cleaned_data.get("password")
#         user = authenticate(self.request, username=username, password=password)
#         if user is not None:
#             login(self.request, user)
#         return super().form_valid(form)

#     def get_success_url(self):
#         next_arg = self.request.GET.get("next")
#         if next_arg is not None:
#             return next_arg
#         else:
#             return reverse("pages:home")


def log_out(request):
    messages.info(request, f"See you later {request.user.first_name}")
    logout(request)
    return redirect(reverse("pages:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_url = self.request.GET.get("next") or "/"
        return resolve_url(next_url)


# mixins.LoggedOutOnlyView,

templates/users/login.html
<form name="loginform" id="loginform" method="POST" action="{% url 'user:ajaxlogin' %}">
    {% csrf_token %}
    <p id="login_error" style="visibility: hidden; color: red;">
        아이디와 비밀번호가 일치하지 않습니다.
        <a href="/user/password/reset/" style="font-size: 0.8rem;color: #5eacff;">
            [비밀번호 찾기]
        </a>
    </p>
    <p id="recaptcha_error" style="display: none; color: red;">
        로봇 검증에 실패하였습니다.
        <a style="font-size: 0.8rem;color: #5eacff; cursor: pointer;" onclick="location.reload()">
            [새로고침]
        </a>
    </p>
    <input id="login_username" class="login_field" type="username" name="username" placeholder="ID" required="">
    <input id="login_password" class="login_field" type="password" name="password" placeholder="비밀번호" required="">
    <input id="recaptcha" class="django-recaptcha-hidden-field" type="hidden" data-sitekey="6Lcuh54eAAAAACY5j3-QpE8AXJLTSumFrlXQN5gW">
    {% comment %} <input id="recaptcha" class="django-recaptcha-hidden-field" type="hidden" name="g-recaptcha-response" value="03AGdBq26p3fWL74spmpuQEVbx-kPaovJqISZ16yOphmLUy8QPTob5yefcRaAAG637i8hwi8p4ABAJKb5X5pJveie5isNLZ0fS_WeDJJJmL8Ldymk018cvW_gqfdMXztHr4tzmfyqkQA29yAWlBG1BBuvcxrDBmYtVF1TLE--oMQPeUA4ahAcwZ9eL8h7XwhB_awm-ihq9WPUIaBFQlcT_aSGsr2c9fIDh6NINUbR8y9yFVKwYAql8y1FHBkrakLD1T2cLSLNomd7gQNZP87PuHXFdKmTTu6GR-CC6cvu3GRECIpBa-vMQE-_25FMV7PIe88Xi4-g8u09zdiAmnH8KqvhACEdjCaB9TSbe2hk8gNRP1OXXXWU9teDUl0lo7oaOMoqVNrTs0wCJihU087mSLZ1KinLquLOqYF8Sh234WTdvprmerJXtaLWDUKdHrmFzzOGFWG25d7hw"> {% endcomment %}
    <div class="counsel_write_btn login_chunk_buttons" style="width: 100%; float:none;">
        <button type="button" style="width: 100%; cursor:pointer;" name="login_submit" class="counsel_cancel popup_login__button" data-next="" onclick="CheckLogin(this.dataset.next)">로그인</button>
        <a href="/user/signup/?next={{request.path}}">
            <button type="button" class="counsel_submit" style="width: 100%; cursor:pointer;">회원가입</button>
        </a>
        <a href="/auth/naver/login/?method=oauth2&amp;next=/">
            <button type="button" class="counsel_submit" style="width: 100%; background-color:#07CF5C; color:white; border:0; cursor:pointer;">
                <svg width="11" height="11" viewBox="0 0 82 82" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 81V1H25L56 43.5V1H81V81H56.5L26 38V81H1Z" fill="white" stroke="white"></path>
                </svg>
                네이버 계정으로 로그인
            </button>
        </a>
        <a href="/auth/kakao/login/?method=oauth2&amp;next=/">
            <button type="button" class="counsel_submit" style="width: 100%; background-color:#F6D53E; color:#382828; border:0; cursor:pointer;">
                <svg width="11" height="11" viewBox="0 0 36 34" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M35.0099 15C35.0099 15 35.0099 28 18.0099 28C16.9488 28 15.95 27.9494 15.0099 27.8544C11.2999 30.2544 6 33 6 33L7.50992 25.7043C0.546211 21.9718 1.01 15 1.01 15C1.01 15 0.0099144 1 18.0099 1C36.0099 1 35.0099 15 35.0099 15Z" fill="#191919"></path>
                    <path d="M7.50992 25.7043C0.546211 21.9718 1.01 15 1.01 15C1.01 15 0.0099144 1 18.0099 1C36.0099 1 35.0099 15 35.0099 15C35.0099 15 35.0099 28 18.0099 28C16.9488 28 15.95 27.9494 15.0099 27.8544M7.50992 25.7043L6 33C6 33 11.2999 30.2544 15.0099 27.8544M7.50992 25.7043C9.46174 26.7504 11.9185 27.5421 15.0099 27.8544" stroke="#191919"></path>
                </svg>
                카카오 계정으로 로그인
            </button>
        </a>
    </div>
</form>

templates/users/signup.html
{% extends "base.html" %}
{% block page_title %}회원가입{% endblock page_title %}
{% block head_info %}
    <meta name="description" content="서울 서초구 방배동 이수역치과, 치아교정, 부분교정, 투명교정, 클리피씨, 인비절라인, 임플란트, 치아미백, 충치, 사랑니, 구강검진">
    <meta name="keywords" content="서울 서초구 방배동 이수역치과, 투명교정, 클리피씨, 치아교정, 부분교정, 인비절라인, 임플란트, 치아미백, 충치, 사랑니, 인비절라인, 군인교정">
    <meta property="og:title" content="광덕안정치과의원" />
    <meta property="og:description" content="광덕안정치과의원" />
    <meta name="twitter:title" content="광덕안정치과의원" />
    <meta name="twitter:description" content="광덕안정치과의원" />
    {% include "mixins/sub_style.html" %}
    <style>
        .grecaptcha-badge{
            display:none;
        }
    </style>
    <style>
        .signup_bottom {
            display: flex;
            justify-content: space-between;
            width: 100%;
        }
    </style>
    <script>
        grecaptcha.ready(function() {
            var grecaptcha_execute = function(){
        grecaptcha.execute('6LedxqgdAAAAADpJQx7JfzW06Fk8VoBE_xYps1PE', {action: 'submit'}).then(function(token) {
            document.querySelectorAll('input.django-recaptcha-hidden-field').forEach(function (value) {
                value.value = token;
            });
            return token;
        })
    };
    grecaptcha_execute()
    setInterval(grecaptcha_execute, 120000);
    
    
        });
    </script>
{% endblock head_info %}


{% block body_info %}
        <div class="container">
            <div class="pagetop pagetop1">
                <div class="page_hgroup com">
                    <h1>커뮤니티</h1>
                    <ul class="catewrap">
                        <!-- 활성화시 class.active 효과 추가해주세요 -->
                        <li class="category">
                            <a href="/posts/notice">공지사항 / 이벤트</a>
                        </li>
                        <li class="category">
                            <a href="/posts/beforeafter">치료 전후사진</a>
                        </li>
                        <li class="category">
                            <a href="/posts/qna">온라인상담</a>
                        </li>
                        <li class="category">
                            <a href="/posts/news">언론보도</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="contents subnotice">
            <div class="center" style="width:400px;">
                <h1 class="subtitle" style="text-align: center;">간편  회원가입</h1>
        
                <!-- 게시판 목록 시작 -->
                <div class="tbl_counsel_write">
                    
        
                    <form class="signup" id="signup_form" method="POST" enctype="multipart/form-data">

                        {% csrf_token %}    
                        
                        
                        
                        <input type="text" name="username" placeholder="아이디" maxlength="150" style="margin-bottom:10px;" required="" id="id_username">
                        
                        
                        <input type="email" name="email" placeholder="이메일 주소" maxlength="254" style="margin-bottom:10px;" id="id_email">
                        
                        
                        <input type="hidden" class="django-recaptcha-hidden-field" name="g-recaptcha-response" value="03AGdBq24rreTvpcho9hAZqAB3GD68xcHfgTRi2dFgfHQnrxXgqh_TWUcz6QbDaoRrbjxVy1ypclIb2RwR68iVwRL1iKnLL7HW4cZEZSv3Ni7fMXY3mQ8MVJDBfIfgMzAxqNIt8LtaMW3Zleej5KU8G34_X7uGh1AHWRAk2_UGpVZWsJHg-Puof4_Wpw4CThUFLTDbm-_LJWDDMbsBVPXd5l6MQyvwRX0wIq4EvNNmVyKobOwbEEHMBuTuiJ4JGN6lkU0uJSQBcE2kBvsEMqM2GmiVbXfak0x3O7qQwbcQ7fDp6UubsZfbCXKaDy3Nrk-BX8IOeiUumeHhRXJkzH1bSE1lnZFWifn2Oaa6He2n4HXMrDNRS1BePPf9mpGLR6WWdfHH9qEdMiMXyb8idx3uzWyJDCa7MbTRu9plsdqhbriNzhkOrapjAKBNdDSXU6aM7YDGJDIKbipY">
                        
                        
                        <input type="password" name="password" placeholder="비밀번호" style="margin-bottom:10px;" required="" id="id_password">
                        
                        
                        <input type="password" name="password1" placeholder="비밀번호 확인" style="margin-bottom:10px;" required="" id="id_password1">
                        
                        {% for field in form %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p style="color:red;">{{error}}</p>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                        <!-- <input type="hidden" id="recaptcha" class="django-recaptcha-hidden-field" name="g-recaptcha-response" value="" /> -->
                        {% comment %} <input type="hidden" name="next" value="{{request.get_full_path}}"> {% endcomment %}
                        <div class="counsel_write_btn signup_bottom" style="display:flex; flex-direction:column;">
                            <div>
                                <input type="checkbox" id="write_chk" style="width:12px; height:12px;" checked="">
                                <label for="write_chk">개인정보 수집 및 이용에 동의합니다 <a href="javascript:;" data-target="perinfo" onclick="popChunkUp(this)">[보기]</a></label>
                            </div>
                            <div class="check-agree" style=" text-align: center; margin: 10px;">
                                <button class="counsel_cancel" type="submit">
                                    회원가입
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
{% endblock body_info %}
{% block sub_script %}
    {% include "mixins/sub_script.html" %}
{% endblock sub_script %}